buildscript {
    repositories {
        maven { url "https://maven.mozilla.org/maven2/" }
        mavenCentral()
        google()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.13.2"
    }
}

allprojects {
    repositories {
        maven { url "https://maven.mozilla.org/maven2/" }
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}
